name: Continuous Integration
on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        fortran-compiler: [gfortran-8, ifort] # [gfortran-8, gfortran-9, nvfortran, ifort]
        rte-kernels: [default, openacc]
    env:
      FC: ${{ matrix.fortran-compiler }}
      NCHOME: /usr
      NFHOME: /usr
      # Defaults for gfortran, over-ridden below
      FCFLAGS: "-ffree-line-length-none -m64 -std=f2008 -march=native -fbounds-check -finit-real=nan -DUSE_CBOOL"
      CC: gcc
    steps:
    #
    # Checks-out repository under $GITHUB_WORKSPACE
    #
    - uses: actions/checkout@v2
    #
    # Set up Python and dependencies
    #
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        python-version: 3.7
    - name: Install python dependencies
      run: conda install --yes urllib3 netcdf4 xarray dask scipy matplotlib seaborn colorcet
    #
    # Install  NetCDF library
    #
    - name: Install netcdf C library
      run: |
        sudo apt-get update
        sudo apt-get install libnetcdf-dev
    # Intel compilers and libraries if needed
    #   https://software.intel.com/content/www/us/en/develop/articles/oneapi-repo-instructions.html#aptpkg
    #
    - name: Intel setup compilers, environment
      if: contains(matrix.fortran-compiler, 'ifort')
      run: |
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
        sudo apt-get update
        sudo apt-get install intel-oneapi-common-licensing
        sudo apt-get install intel-oneapi-common-vars
        sudo apt-get install intel-oneapi-dev-utilities
        sudo apt-get install intel-oneapi-icc
        sudo apt-get install intel-oneapi-ifort
        echo "::set-env name=FC::ifort"
        echo "::set-env name=CC::icc"
        echo "::set-env name=FCFLAGS::'-m64 -g  -traceback -heap-arrays -assume realloc_lhs -extend-source 132 -check bounds,uninit,pointers,stack -stand f08'"
    - name: Nvidia setup compilers, environment
      if: contains(matrix.fortran-compiler, 'nvfortran')
      run: |
        wget -q https://developer.download.nvidia.com/hpc-sdk/nvhpc-20-7_20.7_amd64.deb https://developer.download.nvidia.com/hpc-sdk/nvhpc-2020_20.7_amd64.deb
        sudo apt-get install ./nvhpc-20-7_20.7_amd64.deb ./nvhpc-2020_20.7_amd64.deb
        echo "::set-env name=FC::nvfortran"
        echo "::set-env name=CC::nvcc"
        echo "::set-env name=FCFLAGS::'-Mallocatable=03 -Mstandard -Mbounds -Mchkptr -Kieee -Mchkstk'"
    #
    # NetCDF FORTRAN library
    #
    - name: Build NetCDF Fortran library
      run: |
        echo "FC is " ${FC}
        echo "CC is " ${CC}
        echo FCFLAGS is ${FCFLAGS}
        which ${FC}
        source /opt/intel/oneapi/setvars.sh || true
        git clone https://github.com/Unidata/netcdf-fortran.git --branch v4.4.4
        cd netcdf-fortran
        ./configure --prefix=${NFHOME} CC=${CC}
        make
        sudo make install
    - name: Stage RFMIP files
      run: |
        export RRTMGP_ROOT=${GITHUB_WORKSPACE}
        cd ${RRTMGP_ROOT}/examples/rfmip-clear-sky
        python ./stage_files.py
    - name: Make library, examples, tests
      # Compiler flags for gfortran 8 and 9. Over-ridden in run script if using ifort
      run: |
        export RRTMGP_ROOT=${GITHUB_WORKSPACE}
        export RTE_KERNELS=${{ matrix.rte-kernels }}
        source /opt/intel/oneapi/setvars.sh || true
        cd ${RRTMGP_ROOT}
        ${FC} --version
        make -C build -j 2
        make -C tests -j 1
        make -C examples/all-sky -j 2
        export RRTMGP_BUILD=${RRTMGP_ROOT}/build
        make -C examples/rfmip-clear-sky -j 2
    - name: Run examples, tests
      run: |
        export RRTMGP_ROOT=${GITHUB_WORKSPACE}
        source /opt/intel/oneapi/setvars.sh || true
        cd ${RRTMGP_ROOT}/examples/rfmip-clear-sky
        python ./run-rfmip-examples.py --block_size 8
        cd  ${RRTMGP_ROOT}/examples/all-sky
        python ./run-allsky-example.py
        cd  ${RRTMGP_ROOT}/tests
        cp ${RRTMGP_ROOT}/examples/rfmip-clear-sky/multiple_input4MIPs_radiation_RFMIP_UColorado-RFMIP-1-2_none.nc test_atmospheres.nc
        ./clear_sky_regression test_atmospheres.nc ${RRTMGP_ROOT}/rrtmgp/data/rrtmgp-data-lw-g256-2018-12-04.nc
        ./clear_sky_regression test_atmospheres.nc ${RRTMGP_ROOT}/rrtmgp/data/rrtmgp-data-sw-g224-2018-12-04.nc
    - name: Comparison
      run: |
        export RRTMGP_ROOT=${GITHUB_WORKSPACE}
        cd ${RRTMGP_ROOT}/examples/rfmip-clear-sky
        python ./compare-to-reference.py --fail=7.e-4
        cd ${RRTMGP_ROOT}/examples/all-sky
        python ./compare-to-reference.py
        cd ${RRTMGP_ROOT}/tests
        python verification.py
    - name: Validation plots
      run: |
        export RRTMGP_ROOT=${GITHUB_WORKSPACE}
        cd ${RRTMGP_ROOT}/tests
        python validation-plots.py
    - name: Upload plots
      if: contains(matrix.fortran-compiler, 'ifort') && contains(matrix.rte-kernels, 'default')
      uses: actions/upload-artifact@v2
      with:
        name: valdiation-plot
        path: tests/validation-figures.pdf
